api = "0.4"

[buildpack]
  id = "paketo-buildpacks/rails-assets"
  name = "Paketo Rails Assets Buildpack"
  homepage = "https://github.com/paketo-buildpacks/rails-assets"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
